sudo: false
language: node_js
node_js:
    - "6"
    - "4"
    - "0.10"

services:
  - docker

script:
  # https://docs.travis-ci.com/user/docker/
  - docker pull enkeys/alpine-openjdk-amq7-snapshot
  - docker run --rm -v`pwd`/scripts:/mnt -p 5672:5672 -p 61616:61616 --entrypoint ash enkeys/alpine-openjdk-amq7-snapshot /mnt/entrypoint.sh amq7-server &
  - sleep 10
  - npm run-script browserify
  - npm run-script test