# Test against the latest version of this Node.js version
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "1.0"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - ps: Invoke-webrequest "https://www.apache.org/dyn/closer.cgi?filename=activemq/activemq-artemis/2.1.0/apache-artemis-2.1.0-bin.zip&action=download" -OutFile ".\apache-artemis-2.1.0-bin.zip"
  - ps: 7z x apache-artemis-2.1.0-bin.zip
  - ps: .\apache-artemis-2.1.0\bin\artemis create amq-server --user=admin --password=admin --nio --allow-anonymous
  - ps: Start-process -FilePath .\amq-server\bin\artemis.cmd -ArgumentList ('run') -NoNewWindow
  - ps: Start-Sleep -Seconds 5
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run-script browserify
  - npm run-script test

# Don't actually build.
build: off
